let icons = [
  "/img/menu.png",
  "/img/menu1.png",
  "/img/menu2.png",
  "/img/menu3.png",
  "/img/menu4.png",
  "/img/menu5.png",
  "/img/menu6.png",
  "/img/menu7.png",
  "/img/menu8.png",
  "/img/menu9.png",
  "/img/menu10.png",
  "/img/menu11.png",
  "/img/menu12.png",
  "/img/menu13.png",
  "/img/menu14.png",
  "/img/menu15.png",
  "/img/menu16.png",
  "/img/menu17.png",
  "/img/menu18.png",
];
export default icons;
